"""increase financial_entries.amount precision

Revision ID: 0f7a1e346451
Revises: 16385e2908bb
Create Date: 2026-08-16 11:53:57.747835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f7a1e346451'
down_revision: Union[str, Sequence[str], None] = '16385e2908bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_entries', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_entries', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###
