"""add quantity and price_asset_id to financial_entries

Revision ID: 16385e2908bb
Revises: ac6b7b653f7a
Create Date: 2026-08-16 11:37:29.094982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16385e2908bb'
down_revision: Union[str, Sequence[str], None] = 'ac6b7b653f7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_entries', sa.Column('quantity', sa.Numeric(precision=30, scale=10), nullable=True))
    op.add_column('financial_entries', sa.Column('price_asset_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_entries', 'price_asset_id')
    op.drop_column('financial_entries', 'quantity')
    # ### end Alembic commands ###
