"""add average_cost_basis to financial_entries

Revision ID: 2a3e18f4ce49
Revises: 0f7a1e346451
Create Date: 2026-08-16 12:47:21.462155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a3e18f4ce49'
down_revision: Union[str, Sequence[str], None] = '0f7a1e346451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('average_cost_basis', sa.Numeric(precision=20, scale=8), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_entries', schema=None) as batch_op:
        batch_op.drop_column('average_cost_basis')

    # ### end Alembic commands ###
