"""initial schema

Revision ID: 2d971a3ff7ee
Revises: 
Create Date: 2026-08-16 10:52:19.645382

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2d971a3ff7ee'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_data_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_endpoint', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ok', 'unavailable', 'error', name='datapointstatus', native_enum=False, length=16), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('as_of', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_data_points'))
    )
    op.create_index('ix_market_data_metric_fetched_at', 'market_data_points', ['metric', 'fetched_at'], unique=False)
    op.create_index('ix_market_data_metric_status', 'market_data_points', ['metric', 'status'], unique=False)
    op.create_table('scoring_weights_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('valuation_weight', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('sentiment_weight', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('cycle_weight', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('macro_weight', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('momentum_weight', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('onchain_weight', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scoring_weights_configs'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('financial_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.Enum('income', 'expense', 'asset', 'liability', name='entrytype', native_enum=False, length=16), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('subcategory', sa.String(length=32), nullable=True),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_financial_entries_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_entries'))
    )
    op.create_index(op.f('ix_financial_entries_snapshot_date'), 'financial_entries', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_financial_entries_user_id'), 'financial_entries', ['user_id'], unique=False)
    op.create_table('net_worth_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('total_assets', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_liabilities', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('net_worth', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cash_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('investments_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_net_worth_snapshots_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_net_worth_snapshots')),
    sa.UniqueConstraint('user_id', 'snapshot_date', name='uq_net_worth_user_date')
    )
    op.create_index(op.f('ix_net_worth_snapshots_snapshot_date'), 'net_worth_snapshots', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_net_worth_snapshots_user_id'), 'net_worth_snapshots', ['user_id'], unique=False)
    op.create_table('score_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score_date', sa.Date(), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('subscores_json', sa.JSON(), nullable=False),
    sa.Column('weights_config_id', sa.Integer(), nullable=False),
    sa.Column('inputs_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['weights_config_id'], ['scoring_weights_configs.id'], name=op.f('fk_score_history_weights_config_id_scoring_weights_configs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_score_history'))
    )
    op.create_index(op.f('ix_score_history_score_date'), 'score_history', ['score_date'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.Enum('buy', 'sell', 'deposit', 'withdrawal', 'fee', 'dividend', 'interest', name='transactiontype', native_enum=False, length=16), nullable=False),
    sa.Column('asset', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('fee', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('raw_row_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_transactions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['date'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_score_history_score_date'), table_name='score_history')
    op.drop_table('score_history')
    op.drop_index(op.f('ix_net_worth_snapshots_user_id'), table_name='net_worth_snapshots')
    op.drop_index(op.f('ix_net_worth_snapshots_snapshot_date'), table_name='net_worth_snapshots')
    op.drop_table('net_worth_snapshots')
    op.drop_index(op.f('ix_financial_entries_user_id'), table_name='financial_entries')
    op.drop_index(op.f('ix_financial_entries_snapshot_date'), table_name='financial_entries')
    op.drop_table('financial_entries')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('scoring_weights_configs')
    op.drop_index('ix_market_data_metric_status', table_name='market_data_points')
    op.drop_index('ix_market_data_metric_fetched_at', table_name='market_data_points')
    op.drop_table('market_data_points')
    # ### end Alembic commands ###
