"""add source to financial_entries and unique constraint to transactions

Revision ID: 7b41a43d7e5a
Revises: 2a3e18f4ce49
Create Date: 2026-08-16 14:38:24.841170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b41a43d7e5a'
down_revision: Union[str, Sequence[str], None] = '2a3e18f4ce49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=32), server_default='manual', nullable=False))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_transaction_user_source_external_id', ['user_id', 'source', 'external_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_transaction_user_source_external_id', type_='unique')

    with op.batch_alter_table('financial_entries', schema=None) as batch_op:
        batch_op.drop_column('source')

    # ### end Alembic commands ###
